// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALezZaISWc26875mB8Q9WfySu4kTCxlyU',
    appId: '1:318611568526:web:5d38cc07d8951c929a56df',
    messagingSenderId: '318611568526',
    projectId: 'principal-project-flutter',
    authDomain: 'principal-project-flutter.firebaseapp.com',
    storageBucket: 'principal-project-flutter.firebasestorage.app',
    measurementId: 'G-3SKVY7S4BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJubrO1UeXxUQ9TbC03lbA_IW72ZoTk4',
    appId: '1:318611568526:android:18979060e24dab1d9a56df',
    messagingSenderId: '318611568526',
    projectId: 'principal-project-flutter',
    storageBucket: 'principal-project-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwRXl6oGUpZnUyiL9lj8g6FQFbSwCt_g',
    appId: '1:318611568526:ios:af270f3963f9f3da9a56df',
    messagingSenderId: '318611568526',
    projectId: 'principal-project-flutter',
    storageBucket: 'principal-project-flutter.firebasestorage.app',
    iosBundleId: 'com.example.principalFlutterProject2',
  );
}
